/**
 * Agent 5 — Ranking Agent.
 *
 * Scores each candidate on three independent axes (saju / preference /
 * distance) so the user can see why a place was picked. Final score uses a
 * fixed weighting that favors saju fit (0.5 / 0.3 / 0.2). The reason text is
 * generated by Solar with the score breakdown + chart facts, so the rationale
 * actually mentions the user's elements rather than only their style picks.
 */

import type { TravelRange, UserInput } from '../../src/types';
import type {
  CandidateDestination,
  RankedDestination,
  SajuAnalysis,
  ScoreBreakdown,
  TravelStyleMapping,
} from '../types';
import { TRAVEL_STYLES } from '../../src/mocks/travelStyles';
import { ELEMENT_TRAVEL_AFFINITY } from '../saju/baziCalculator';
import { callSolarJson, type ChatMessage } from '../solar';

const WEIGHT_SAJU = 0.5;
const WEIGHT_PREFERENCE = 0.3;
const WEIGHT_DISTANCE = 0.2;

const RANGE_LIMITS: Record<TravelRange, number> = {
  '2시간 이내': 2,
  '4시간 이내': 4,
  '제한 없음': 8,
};

function computeSajuScore(
  d: CandidateDestination,
  saju: SajuAnalysis,
): number {
  // 0–100 scale.
  let s = 0;
  // Boost-target element match — strongest signal.
  if (d.elementAffinity.includes(saju.needsBoost)) s += 60;
  // Already-strong element match — light bonus, but heavily reduced because
  // we want balance, not amplification of dominance.
  saju.elements.strong.forEach((el) => {
    if (el === saju.needsBoost) return;
    if (d.elementAffinity.includes(el)) s += 8;
  });
  // Day master element echo — small bonus.
  if (d.elementAffinity.includes(saju.chart.dayMaster.element)) s += 12;
  // Dominant overload penalty: if the destination only echoes the already
  // dominant element and offers no boost element, reduce.
  const onlyDominant =
    d.elementAffinity.length > 0 &&
    d.elementAffinity.every((e) => e === saju.elements.dominant) &&
    !d.elementAffinity.includes(saju.needsBoost);
  if (onlyDominant) s -= 20;
  return clamp(s, 0, 100);
}

function computePreferenceScore(
  d: CandidateDestination,
  input: UserInput,
  mapping: TravelStyleMapping,
): number {
  let s = 0;
  // User-picked tag overlap.
  const userOverlap = d.tags.filter((t) => input.preferredStyles.includes(t)).length;
  s += userOverlap * 18;
  // Mapping preferred tag overlap.
  const mapOverlap = d.tags.filter((t) => mapping.preferredTags.includes(t)).length;
  s += mapOverlap * 8;
  // Style category match.
  if (d.styles.includes(mapping.primary)) s += 20;
  if (mapping.secondary && d.styles.includes(mapping.secondary)) s += 10;
  // Avoid-tag penalty.
  const avoidHits = d.tags.filter((t) => mapping.avoidTags.includes(t)).length;
  s -= avoidHits * 6;
  return clamp(s, 0, 100);
}

function computeDistanceScore(
  d: CandidateDestination,
  input: UserInput,
): number {
  const t = d.travelTime[input.departure];
  const limit = RANGE_LIMITS[input.travelRange];
  if (t > limit) return 0;
  // Closer = higher. 1 hour → ~95, equal to limit → ~50.
  const ratio = 1 - t / Math.max(limit, 1);
  let s = 50 + ratio * 50;
  // Day-trip bonus.
  if (input.travelDuration === '당일' && t <= 2) s += 5;
  return clamp(s, 0, 100);
}

interface LlmReasonPayload {
  reasons: Array<{ id: string; reason: string }>;
}

const SYSTEM_PROMPT = `당신은 사주 명리학에 기반한 여행 큐레이터입니다.
각 여행지에 대해 왜 이 사용자에게 어울리는지 한국어 1~2문장으로 설명하세요.
규칙:
- 반드시 사용자의 부족한 오행(보완 필요)을 한 번 이상 언급하고, 어떤 환경 요소가 그 오행을 보완하는지 연결합니다.
- 선호 스타일이 있다면 어떻게 결합되는지도 자연스럽게 녹이세요.
- "재미·참고용" 어조를 유지하고 단정하지 마세요.
- 출력은 반드시 단일 JSON 객체로 합니다. {"reasons":[{"id":"...","reason":"..."}]}`;

export async function runRanking(
  input: UserInput,
  saju: SajuAnalysis,
  mapping: TravelStyleMapping,
  candidates: CandidateDestination[],
  apiKey: string,
  model?: string,
): Promise<RankedDestination[]> {
  const scored = candidates.map((d) => {
    const sajuScore = computeSajuScore(d, saju);
    const prefScore = computePreferenceScore(d, input, mapping);
    const distScore = computeDistanceScore(d, input);
    const total =
      sajuScore * WEIGHT_SAJU +
      prefScore * WEIGHT_PREFERENCE +
      distScore * WEIGHT_DISTANCE;
    const breakdown: ScoreBreakdown = {
      saju: round1(sajuScore),
      preference: round1(prefScore),
      distance: round1(distScore),
      total: round1(total),
    };
    return { d, breakdown };
  });

  scored.sort((a, b) => b.breakdown.total - a.breakdown.total);
  const top3 = scored.slice(0, 3);

  // Build reasons via Solar (one call covering all 3 destinations).
  const reasonMap = await fetchReasons(top3, input, saju, mapping, apiKey, model);

  return top3.map(({ d, breakdown }) => ({
    destination: d,
    score: breakdown,
    reason: reasonMap[d.id] ?? buildFallbackReason(d, saju, mapping),
  }));
}

async function fetchReasons(
  top: Array<{ d: CandidateDestination; breakdown: ScoreBreakdown }>,
  input: UserInput,
  saju: SajuAnalysis,
  mapping: TravelStyleMapping,
  apiKey: string,
  model?: string,
): Promise<Record<string, string>> {
  const userPrompt = [
    `일간: ${saju.chart.dayMaster.stem}(${saju.chart.dayMaster.element})`,
    `보완 필요한 오행: ${saju.needsBoost} (${ELEMENT_TRAVEL_AFFINITY[saju.needsBoost].environments.join('/')} 같은 환경이 도움)`,
    `강한 오행: ${saju.elements.strong.join(', ') || '뚜렷하지 않음'}`,
    `매핑된 스타일: ${TRAVEL_STYLES[mapping.primary].label}${mapping.secondary ? ` + ${TRAVEL_STYLES[mapping.secondary].label}` : ''}`,
    `사용자 선호 태그: ${input.preferredStyles.join(', ') || '없음'}`,
    '',
    '아래 각 여행지에 대한 추천 이유를 1~2문장씩 작성해 주세요. 사주 보완 오행을 반드시 언급하세요.',
    ...top.map(({ d, breakdown }, i) =>
      `${i + 1}. id=${d.id} | ${d.name}(${d.region}) | 태그: ${d.tags.join(', ')} | 사주점수: ${breakdown.saju} / 선호: ${breakdown.preference} / 거리: ${breakdown.distance}`,
    ),
    '',
    'JSON 형식: {"reasons":[{"id":"<id>","reason":"<문장>"}, ...]}',
  ].join('\n');

  try {
    const res = await callSolarJson<LlmReasonPayload>(
      [
        { role: 'system', content: SYSTEM_PROMPT },
        { role: 'user', content: userPrompt },
      ] satisfies ChatMessage[],
      { apiKey, model, temperature: 0.5, maxTokens: 700 },
    );
    const out: Record<string, string> = {};
    res.reasons?.forEach((r) => {
      if (r.id && r.reason) out[r.id] = r.reason;
    });
    return out;
  } catch (err) {
    console.warn('[ranking] Solar fallback for reasons:', (err as Error).message);
    return {};
  }
}

function buildFallbackReason(
  d: CandidateDestination,
  saju: SajuAnalysis,
  mapping: TravelStyleMapping,
): string {
  const env = ELEMENT_TRAVEL_AFFINITY[saju.needsBoost].environments[0];
  const styleLabel = TRAVEL_STYLES[mapping.primary].label;
  return `${saju.needsBoost}(${saju.needsBoost}) 기운이 부족한 지금, ${d.name}의 ${env} 결이 균형을 맞춰 줍니다. ${styleLabel}의 흐름과도 자연스럽게 이어져요.`;
}

function clamp(v: number, lo: number, hi: number): number {
  return Math.max(lo, Math.min(hi, v));
}

function round1(v: number): number {
  return Math.round(v * 10) / 10;
}
